name: flutter_typeahead
version: 5.2.0

description: A highly customizable typeahead (autocomplete) text input field for Flutter
homepage: https://github.com/AbdulRahmanAlHamali/flutter_typeahead

environment:
  sdk: ">=2.7.0 <=3.7.7"

dependencies:
  flutter:
    sdk: flutter
  flutter_keyboard_visibility_temp_fork: ^0.1.4
  #pointer_interceptor: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
